import { NextIntlClientProvider } from "next-intl";

import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import GuestNavbar from "./components/base/GuestNavbar";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.variable} antialiased`}>
        <NextIntlClientProvider>
          <GuestNavbar />
          <div className="flex min-h-screen items-center justify-center">
            {children}
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
